import { annotationStore } from "@hdwlab/api-annotation-store-client";
import { useAPIClient, useAPIClientWithSWR } from "@hdwlab/api-helper-typescript";
import { useMemo } from "react";
import { useDatabaseRecordId } from "../../hooks/useDatabaseRecordId";
import { AnnotationForCoMLOpsPromptEngineeringEx2, UserInputAnnotation } from "./types";

const API_VERSION = "dataware-tools.com/v1alpha5";
const ANNOTATION_TASK_ID = "comlops-pe-ex2";
export const useAddAnnotation = () => {
  const { databaseId, recordId } = useDatabaseRecordId();

  const client = useAPIClient();

  const request = async (annotation: UserInputAnnotation) => {
    // @ts-expect-error annotation_id and generation is automatically generated by the server
    const annotationInRequestObject: AnnotationForCoMLOpsPromptEngineeringEx2 = {
      _api_version: API_VERSION,
      _kind: "ArbitraryAnnotation",
      timestamp_from: annotation.timestampFrom,
      timestamp_to: annotation.timestampTo,
      record_id: recordId,
      annotation_task_id: ANNOTATION_TASK_ID,
      annotation: {
        tag_type: annotation.tagType,
        tags: annotation.tags.map((tag) => tag.value),
        note: annotation.note,
      },
    };

    const response = await client(
      annotationStore.Configuration,
      annotationStore.AnnotationApi,
      "createAnnotation",
      {
        databaseId,
        annotation: annotationInRequestObject,
      },
    );
    return response;
  };

  return { request };
};

export const useUpdateAnnotation = () => {
  const { databaseId } = useDatabaseRecordId();

  const client = useAPIClient();

  const request = async (annotation: AnnotationForCoMLOpsPromptEngineeringEx2) => {
    const annotationInRequestObject: annotationStore.Annotation = {
      ...annotation,
      generation: annotation.generation + 1,
    };

    const response = await client(
      annotationStore.Configuration,
      annotationStore.AnnotationApi,
      "updateAnnotation",
      {
        databaseId,
        annotationId: annotation.annotation_id,
        annotation: annotationInRequestObject,
      },
    );
    return response;
  };

  return { request };
};

export const useDeleteAnnotation = () => {
  const { databaseId } = useDatabaseRecordId();

  const client = useAPIClient();

  const request = useMemo(
    () => async (annotationId: string) => {
      const response = await client(
        annotationStore.Configuration,
        annotationStore.AnnotationApi,
        "deleteAnnotation",
        {
          databaseId,
          annotationId,
        },
      );
      return response;
    },
    [databaseId, client],
  );

  return { request };
};

export const useServerAnnotations = () => {
  const { databaseId, recordId } = useDatabaseRecordId();
  const { data, mutate } = useAPIClientWithSWR({
    APIClientClass: annotationStore.AnnotationApi,
    APIConfigurationClass: annotationStore.Configuration,
    operationId: "searchAnnotation",
    params: {
      databaseId,
      searchAnnotationRequest: {
        query: {
          $and: [{ _kind: "ArbitraryAnnotation", annotation_task_id: ANNOTATION_TASK_ID }],
          record_id: recordId,
        },
        per_page: -1,
      },
    },
  });

  return {
    annotations: data?.data as AnnotationForCoMLOpsPromptEngineeringEx2[] | undefined,
    refetchServerAnnotations: mutate,
  };
};
